version: '3.8'

services:
  cms-app:
    build: .
    container_name: lumina-cms
    restart: always
    ports:
      - "5000"
    environment:
      - DB_HOST=${DB_HOST:-45.152.243.96}
      - DB_PORT=${DB_PORT:-3308}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-q8XwstabNctdCkEDp0TEdtlmSUIkdSFpQqhkKr2ANy7MXNl3gD7W6TX93uNVTONw}
      - DB_NAME=${DB_NAME:-default}
      - PORT=5000
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASS=${ADMIN_PASS:-admin123}
